---
title: "Resultados"
format: html
---

## Fluxograma dos participantes

(colocar fluxograma)

## Caracterização da amostra

```{r}
#| echo: false
#| message: false
#| warning: false
#| label: tbl-basal
#| tbl-cap: "Tabela 1: Caracterização basal dos participantes do ensaio Glucocheck."
library(tidyverse)
library(gtsummary)

dados <- read_csv("data/raw/glucocheck.csv")

tabela_basal <- dados |>
  select(grupo, idade, sexo, hba1c_baseline, hba1c_6meses, glicemia_jejum_baseline, glicemia_jejum_6meses, peso_baseline, peso_6meses, des_sf, satisfacao) |>
  tbl_summary(by = grupo) |>
  add_overall() |>
  add_p()
tabela_basal
```

## Resultados Principais

### Outcome primário

```{r}
#| echo: false
#| fig-width: 6
#| fig-height: 4

ggplot(dados |> filter(!is.na(hba1c_6meses)),
    aes(x = grupo, y = hba1c_6meses, colour = grupo)) +
  geom_boxplot(outlier.shape = NA, width = 0.4, linewidth = 0.7) +
  geom_jitter(width = 0.12, alpha = 0.7, size = 2.5) +
  scale_colour_manual(
    values = c("intervencao" = "#2C3E50", "controlo" = "#7A9B9E")
  ) +
  labs(
    x     = "Grupo",
    y     = "Hemoglobina glicada aos 6 meses (%)",
    title = "GlucoCheck"
  ) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "none")
```

### Outcomes Secundários

### Gráficos

(colocar algum gráfico que ajude a visualizar a diferença entre grupos)
